language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install python-coveralls coverage nose-cov
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - echo TRAVIS_PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} != "3" ]; then travis_retry pip install contextlib2; fi
  - python setup.py --version

# Run test
script:
  - nosetests -v --with-cov --cov streamparse --cov-config .coveragerc --logging-level=DEBUG

# Calculate coverage on success
after_success:
  - coveralls --config_file .coveragerc
