language: python

python:
  - "2.7"
  - "3.3"

install:
  - "python setup.py --version"
  - "pip install -r requirements.txt"
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install contextlib2; fi

script: nosetests
